### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wlw191** [ThinkInAIXYZ/go-mcp#164]
## Bug Report: MCP Error -32603: Protocol version not supported, server expects "2024-11-05"

**Describe the bug**
When attempting to connect to a `go-mcp` server (version `v0.2.11`) using a Microsoft Cline plugin (acting as an MCP client via SSE), the server returns an error: `MCP error -32603: protocol version not supported, supported version is 2024-11-05`. This indicates a mismatch between the MCP protocol version expected by the server and the one used by the client.

**To Reproduce**
1. Build and run the `go-mcp` server using the provided `docker-compose.yml` and `Dockerfile` (see "Relevant Files" section below). The `go-mcp` version used is `v0.2.11` as per `go.sum`.
2. Configure the Microsoft Cline plugin (SSE service) to connect as an MCP client to the server endpoint (e.g., `http://localhost:8080`).
3. Observe the error message either in the client or server logs.

**Expected behavior**
The client should successfully connect to the `go-mcp` server, or there should be clear documentation/guidance on version compatibility between `go-mcp` server versions and expected client MCP protocol versions.

**Actual behavior**
The server responds with the error: `MCP error -32603: protocol version not supported, supported version is 2024-11-05`

**Screenshots or Logs**
Error message from the client/server:
**Environment (please complete the following information):**
*   **`go-mcp` Server Version:** `v0.2.11` (from `go.sum`: `github.com/ThinkInAIXYZ/go-mcp v0.2.11`)
*   **Go Version (for building server):** `1.24` (from Dockerfile: `golang:1.24-alpine`)
*   **Client:** Microsoft Cline plugin (specific version initiating the MCP call is unknown, but it's not using "2024-11-05")
*   **OS (running Docker host):** [Please fill in your OS, e.g., Linux Ubuntu 22.04, macOS Sonoma, Windows 11]

**Relevant Files:**

**`docker-compose.yml`:**
```yaml
version: '3.8'
services:
  serp-mcp-server:
    build:
      context: .. # 构建上下文是项目根目录
      dockerfile: deploy/Dockerfile # Dockerfile 的路径相对于 context
      args:
        # 将主机环境的代理变量传递给构建参数
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    container_name: serp-mcp
    restart: unless-stopped
    ports:
      # 将主机的 8080 端口映射到容器的 8080 端口
      # 格式: "HOST:CONTAINER"
      - "8080:8080"
    environment:
      - SERPAPI_KEYS=${SERPAPI_KEYS}
      - LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0:8080} # 使用环境变量或默认值
# 注意: 为了使用 ${SERPAPI_KEYS}，您需要在运行 docker-compose up 之前
# 在当前目录 (deploy/) 创建一个 .env 文件，内容类似：
# SERPAPI_KEYS=YOUR_API_KEY_1,YOUR_API_KEY_2,...
# 或者在运行命令时直接设置环境变量:
# SERPAPI_KEYS="key1,key2" docker-compose up -d
```
**`Dockerfile`:**
```yaml
# --- Build Stage ---
FROM golang:1.24-alpine AS builder
WORKDIR /app
# 复制 Go 模块文件并下载依赖项 (利用 Docker 缓存)
COPY go.mod go.sum ./
RUN go mod download
# 复制源代码
COPY . .
# 构建 Go 应用程序
# CGO_ENABLED=0 禁用 CGO 以便静态链接
# -ldflags="-w -s" 减小二进制文件大小 (移除调试信息和符号表)
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /go-serp-mcp-server ./main.go

# --- Final Stage ---
FROM alpine:latest
# 定义构建参数以接收代理设置
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
# 设置代理环境变量 (如果构建参数被传递)
# apk 等工具会自动使用这些变量
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV NO_PROXY=${NO_PROXY}
# Alpine 需要 ca-certificates 来进行 HTTPS 调用
# 先更新包列表，再安装
RUN apk update && apk --no-cache add ca-certificates
# 清理代理环境变量，避免它们留在最终镜像中
ENV HTTP_PROXY=""
ENV HTTPS_PROXY=""
ENV NO_PROXY=""
WORKDIR /app
# 从构建阶段复制编译好的二进制文件
COPY --from=builder /go-serp-mcp-server /app/go-serp-mcp-server
# 暴露服务器监听的端口 (默认 8080，可以通过 LISTEN_ADDR 环境变量覆盖)
EXPOSE 8080
# 设置默认环境变量 (可以在 docker run 时覆盖)
ENV LISTEN_ADDR=0.0.0.0:8080
ENV SERPAPI_KEYS=""
# 运行应用程序
ENTRYPOINT ["/app/go-serp-mcp-server"]
```
 **`go.sum`:**
```sum
github.com/ThinkInAIXYZ/go-mcp v0.2.11 h1:Qu5BdR2k7EsRcTLValt5aXHb5cfaBRp6G8/2kL0tAMo=
github.com/ThinkInAIXYZ/go-mcp v0.2.11/go.mod h1:KnUWUymko7rmOgzvIjxwX0uB9oiJeLF/Q3W9cRt8fVg=
```
